name: 雷神自动停止加速

on:
  push:
  schedule:
   # 定时任务，北京时间2点执行任务 21 + 8 = 5:00 am
    - cron: '0 21 * * *'

jobs:
  pause:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: "雷神加速器暂停脚本"
        run: |
          node main.js
        env:
          LEISHEN_ACCOUNT_TOKEN: ${{ secrets.LEISHEN_ACCOUNT_TOKEN }}
